name: tsa-lecture
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - scipy
  - ipykernel
  
  - scikit-learn
  - tslearn
  - statsmodels

  - pip
  - pip:
    - meteostat